version: '3.8'

services:
  traefik:
    image: "traefik"
    restart: always
    command:
      - "--api=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=integrations@cliengo.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_network

  fluxia-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fluxia-app
    environment:
      - NODE_ENV=production
      - REACT_APP_ENV=production
    restart: unless-stopped
    networks:
      - fluxia-network
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fluxia-front.devcliengo.com`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.entrypoints=websecure,web"
      - traefik.http.routers.fastapi.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.fastapi.headers.SSLRedirect=true
      - traefik.http.middlewares.fastapi.headers.STSSeconds=315360000
      - traefik.http.middlewares.fastapi.headers.browserXSSFilter=true
      - traefik.http.middlewares.fastapi.headers.contentTypeNosniff=true
      - traefik.http.middlewares.fastapi.headers.forceSTSHeader=true
      - traefik.http.middlewares.fastapi.headers.SSLHost=fluxia-front.devcliengo.com
      - traefik.http.middlewares.fastapi.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.fastapi.headers.STSPreload=true
    networks:
      - traefik_network

networks:
  traefik_network:
    name: traefik_net
    driver: bridge

volumes:
  traefik_acme:
    driver: local