# Static Traefik configuration file
# This file can be used instead of command line arguments

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and dashboard configuration
api:
  dashboard: false
  insecure: false

# Entrypoints configuration
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Providers configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: fluxia-network

# Certificate resolvers for Let's Encrypt
certificatesResolvers:
  letsencrypt:
    acme:
      email: integrations@cliengo.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web

# Logging
log:
  level: INFO
  
accessLog: {}

# Metrics (optional)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true